spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/local-db
    username: my_user
    password: my_pwd

mail:
  base-url:
  from: "no-reply@test.com"
  verify:
    service-name: "Auth-System"

authentication:
  active: false