name: CI + Docker

on:
  push:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make Gradle wrapper executable
        working-directory: ./auth-service
        run: chmod +x gradlew

      - name: Build Spring Boot app with Gradle
        working-directory: ./auth-service
        run: ./gradlew clean build -Dspring.profiles.active=test

      - name: Upload test report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: auth-service/build/reports/tests/test


      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        working-directory: ./auth-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/auth-service:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
